name: {{ NAME }}
description: {{ DESCRIPTION }}
authors: [ {{ AUTHORS }} ]
links:
  website: ...
  source: ...
  issues: ...
  donations: ...

minecraftVersion: {{ MC_VERSION }}
forgeVersion: recommended

# These following defaults defined by default but are provided
# as examples for how to define your own and what's available.
# (You can remove this section if you don't modify anything.)
defaults:
  # Special group * applies to all included resources
  mods:
    path: "mods"
    handler: curse
    version: recommended # or latest
  config:
    path: "config"
    handler: file
  client: { side: client }
  server: { side: server }
  curse: { handler: curse }
  github: { handler: github }
  recommended: { version: recommended }
  latest: { version: latest }

includes:
  
  mods:
    common:
      - https://github.com/ExampleSensei/SampleLib/releases/download/v1.0.0/SampleLib-1.0.0.jar
    github:
      - ExampleSensei/SampleMod @ 2.4.0
    client:
      - BetterShaders @ 1.0.1      # Use @ to select exactly which version to use ..
      - Inventory Recipes @ latest # .. or latest / recommended to override the default.
    server & github & optional & latest: # It's possible to combine defaults.
      - ExampleSensei/AutomaticBackups
